- name: "Create dirs"
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ dir | flatten }}"

- name: "Clone app to folder"
  git:
    repo: "{{ git_app_repo }}"
    dest: "{{ dir }}"

- name: "Clean old app config"
  file:
    path: "{{ app_resourse_path }}/application.yml"
    state: absent

- name: "Create application config file"
  template:
    src: "{{ project_dir_profile }}/{{ profile }}/app/application.yml"
    dest: "{{ app_resourse_path }}/application.yml"

- name: "Build container"
  docker_container:
    name: "{{ app_container_repo }}/{{ app_container_name }}"
    build:
      path: "{{ dir }}/testerization"
    tag: "{{ app_tag }}"
    source: build