- name: "Install simple packages"
  apt:
    name: "{{ simple_apt_packages }}"
    state: present
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ postgres_apt_key }}"
    state: present

- name: "Add repositories"
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ apt_pack_repos | flatten }}"

- name: "Install a apt of packages ansible"
  apt:
    name: "{{ complex_apt_packages }}"
    state: present
    update_cache: yes

- name: "Install pip packages"
  pip:
    name: "{{ pip_packages }}"

- name: "Install terraform switcher"
  shell: "curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash"
  when: terraform_need

- name: "Create gradle dir"
  file:
    path: "/opt/gradle"
    owner: "bilbo"
    group: "admin"
    state: directory

- name: "Download Gradle and unarchive"
  unarchive:
    src: "https://services.gradle.org/distributions/{{ gradle_version }}-bin.zip"
    dest: "/opt/gradle"
    mode: '0774'
    remote_src: yes

- name: "Add gradle to path"
  template:
    src: "{{ project_dir_profile }}/{{ profile }}/environment"
    dest: "/etc/environment"
    state: present

- name: "Update Envs"
  shell:
    cmd: "source /etc/environment"
    executable: /bin/bash