- name: "Install simple packages"
  apt:
    name: "{{ simple-apt-packages }}"
    state: present
    update_cache: yes

- name: "Add repositories"
  apt_repository:
    repo: "{{ apt-pack-repos }}"
    state: present
  loop: "{{ apt-pack-repos }}"

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ postgres-apt-key }}"
    state: present

- name: "Install a apt of packages ansible"
  apt:
    name: "{{ complex-apt-packages }}"
    state: present
    update_cache: yes

- name: "Install pip packages"
  pip:
    name: "{{ pip-packages }}"

- name: "Install terraform switcher"
  shell: "curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash"
  when: "{{ terraform-need }}"

- name: "Download Gradle and unarchive"
  unarchive:
    src: "https://services.gradle.org/distributions/{{ gradle-version }}-bin.zip"
    dest: "/opt/gradle"
    mode: '0774'
    remote_src: yes

- name: "Add gradle to path"
  lineinfile:
    path: /etc/environment
    line: "export PATH=$PATH:/opt/gradle/{{ gradle-version }}/bin"
    state: present

- name: "Update Envs"
  shell: source /etc/environment