variable "name_prefix" {}
variable "family" {}
variable "identifier" {}
variable "parameters" {}
variable "subnet_ids" {}
variable "tags" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "allocated_storage" {}
variable "storage_type" {}
variable "storage_encrypted" {}
variable "name" {}
variable "username" {}
variable "password" {}
variable "port" {}
variable "vpc_security_group_ids" {}
variable "vpc_id" {}
variable "availability_zone" {}
variable "backup_window" {}
variable "backup_retention_period" {}