- name: Create RSA key to be used for ansible account
  openssl_privatekey:
    path: "{{ account_key_path }}"
    size: 4096
    type: RSA

- name: "Generate the private key file to sign the CSR"
  openssl_privatekey:
    path: "{{ private_key_path }}"
    select_crypto_backend: cryptography
    size: 4096
    type: RSA

- name: "Generate the CSR file signed with the private key"
  openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    common_name: "{{ dns_name }}"

- name: "Sign the CSR file to turn it into a certificate"
  openssl_certificate:
    path: "{{ crt_path }}"
    privatekey_path: "{{ private_key_path }}"
    csr_path: "{{ csr_path }}"
    provider: selfsigned
    select_crypto_backend: cryptography
    selfsigned_not_after: +365d
    acme_accountkey_path: "{{ account_key_path }}"