- hosts: "{{ host }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  vars_files:
    - "{{ project_dir_root }}/ansible/group_vars/global_var.yml"
    - "{{ project_dir_root }}/ansible/group_vars/app/app_vars.yml"
    - "{{ project_dir_root }}/ansible/group_vars/docker.yml"

  tasks:
    - include: "{{ project_dir_ansible }}/tasks/common/apt_pack_install.yml"
    - include: "{{ project_dir_ansible }}/tasks/common/pip_pack_install.yml"
    - include: "{{ project_dir_ansible }}/tasks/common/docker_install.yml"